{% set name = "chaco" %}
{% set version = "4.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../chaco/

build:
  string: 4a6683_2
  number: 2
  # script: python setup.py install  --single-version-externally-managed --record=record.txt
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - python
    - setuptools
    - enable >=4.8.0,<4.9
    # - numpy
    - cython
    # - pillow
    # - fonttools
    # - fonttools =4.0.1

  run:
    - python
    - enable >=4.8.0,<4.9
    # - numpy
    - cython
    # - pillow
    # - fonttools
    # - fonttools =4.0.1

test:
  # Python imports
  imports:
    - chaco
    - chaco.contour
    - chaco.downsample
    - chaco.downsample.tests
    - chaco.layers
    - chaco.overlays
    - chaco.plugin
    - chaco.scales
    - chaco.scales.tests
    - chaco.shell
    - chaco.tests
    - chaco.tools
    - chaco.tools.tests
    - chaco.tools.toolbars
    - chaco.ui

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://docs.enthought.com/chaco
  license: BSD License
  summary: 'interactive 2-dimensional plotting'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

extra:
  recipe-maintainers:
    - capn-freako
