package:
  name: parsec
  version: "3.3"

source:
  fn: parsec-3.3.tar.gz
  url: https://pypi.python.org/packages/4c/50/3ca88db4eadd6e4d175b80f6bf47768d4f8bf4c6e9ff5e1ff61eadc64b0c/parsec-3.3.tar.gz
  md5: b120b9effe24c1f7d3d35addf2fda095
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - parsec = parsec:main
    #
    # Would create an entry point called parsec that calls parsec.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - parsec

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/sighingnow/parsec.py
  license: MIT License
  summary: 'parser combinator.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
